# docker-compose.yml
version: '3.3'

services:

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["npm", "start"]
  postgres:
    image: postgres:9.6.14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doremi123!